version: '3.8'

services:
  empty-image:
    build:
      context: .
      dockerfile: Dockerfile
    image: empty-image:latest
    networks:
      - docker-network

  openvpn-server:
    image: kylemanna/openvpn:latest
    container_name: openvpn-server
    ports:
      - "1194:1194/udp"
    volumes:
      - openvpn-data:/etc/openvpn
    networks:
      - docker-network
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.default.forwarding=1
      - net.ipv6.conf.all.forwarding=1
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "netstat", "-tlnup"]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  docker-network:
    driver: bridge

volumes:
  openvpn-data:
    driver: local
